# Ejercicios

# 1. Utilice todos los métodos estudiados (Newton, Bisección y Secante) para encontrar la raíz de la siguiente función: f(x) = x + cos x en el intervalo [-2;0], con cuatro cifras decimales.

In [1]:
import numpy as np
def newton(f,df,x0,nmax,tol):
    xi=x0
    for i in range(0,nmax):
        xi=xi-f(xi)/df(xi)
        if abs(f(xi)) < tol:
            print(xi,' encontrado con ',i,' iteraciones')
            break
    return None

In [2]:
def biseccion(f,a,b,tol,nmax):
    for i in range(1,nmax):
        if np.sign(f(a)) == np.sign(f(b)):
            print("La raíz no está en el intervalo especificado")
            return
        
        m = (a + b)/2
        
        if abs(f(m)) < tol:
            return m
        elif np.sign(f(a)) == np.sign(f(m)):
            a = m
        #elif np.sign(f(b)) == np.sign(f(m)):
        else:
            b = m
        i += i

In [3]:
def biseccion2(f,a,b,tol): 
    if np.sign(f(a)) == np.sign(f(b)):
        print("La raíz no está en el intervalo especificado")
        return
        
    m = (a + b)/2
    
    if np.abs(f(m)) < tol:
        return m
    elif np.sign(f(a)) == np.sign(f(m)):
        return biseccion2(f, m, b, tol)
    elif np.sign(f(b)) == np.sign(f(m)):
        return biseccion2(f, a, m, tol)

In [4]:
def secante(f,x0,x1,nmax,tol):
    for i in range(0,nmax):
        x2=(x0*f(x1)-x1*f(x0))/(f(x1)-f(x0));
        if abs(x2-x1) < tol:
            print(x2,' encontrado con ',i,' iteraciones')
            break
        else:
            x0=x1
            x1=x2
    return None

In [5]:
f = lambda x: x + np.cos(x)
df = lambda x: 1 - np.sin(x)

In [6]:
newton(f,df,-2,100,0.0001)

-0.7390897242053693  encontrado con  1  iteraciones


In [7]:
r1 = biseccion(f, -2, 0, 0.0001,100)
r2 = biseccion2(f, -2, 0, 0.0001)
print(r1,' encontrada por el método de la bisección\n')
print("error =", np.sqrt(2)-r1,'\n')
print("error =", np.sqrt(2)-r2,'\n')

-0.7391357421875  encontrada por el método de la bisección

error = 2.153349304560595 

error = 2.153349304560595 



In [8]:
secante(f,-2,0,50,0.0001)

-0.7390851370199945  encontrado con  4  iteraciones


# 2. Encuentre la intersección de las siguientes funciones: f(x) = 3 - x y g(x) = ln x, con tres cifras decimales.

In [11]:
import math
f = lambda x: 3 - x
df = lambda x: -1
g = lambda x: math.log(x+1e-30) # agrego a x un valor muy muy pequeño para que evitar el error de punto flotante
dg = lambda x: 1/(x+1e-30)

In [12]:
newton(f,df,2,100,0.001)
newton(g,dg,.5,100,0.001)

3.0  encontrado con  0  iteraciones
0.9999225169723374  encontrado con  2  iteraciones


# 3. Programe el método de sustitución regresiva. Analice el número de operaciones del algoritmo para matrices de tamaño 3 x 3.

In [14]:
#import numpy as np
# ingresamos matriz
A = np.array([[1,1,-3],[0,1,1],[0,0,3]])
# terminos independientes
b=np.array([0,1,3])
#el numero de ecuaciones 3 filas
n=np.size(b)
#Definimos el vector para colocar la solucion
x=np.zeros(n)
#hacemos el ciclo que va desde la ultima ecuacion hasta la primera
for i in range(n-1,-1,-1):
    sumj=0
    for j in range (i+1,n):
        sumj +=A[i,j]*x[j]
    x[i]=(b[i]-sumj)*1/A[i,i]
print(x)

[3. 0. 1.]


# 4. Una importante parte de la física es la termodinámica que es el estudio de la transferencia de calor.
# En este ejercicio vamos a determinar la distribución de temperatura de estado estable de una placa delgada cuando se conoce la temperatura en los bordes.
# Suponga que la placa que se ilustra en la figura representa una sección transversal de una viga de metal, con flujo de calor despreciable en la dirección perpendicular a la placa. Sean T1, T2, T3 y T4 las temperaturas en los cuatro nodos interiores de la malla en la figura. La temperatura en un nodo es aproximadamente igual al promedio de las temperaturas de los cuatro nodos más cercanos, esto es, a la izquierda, arriba, a la derecha y abajo.
# Escriba un sistema de ecuaciones cuya solución de estimaciones de las temperaturas T1, T2, T3 y T4.

In [15]:
#import numpy as np
A = np.array([[4., -1., -1.,  0.],
              [-1., 4.,  0., -1.],
              [-1., 0.,  4., -1.],
              [0., -1., -1., 4.]])
B = np.array([30.,60.,40.,70.])
A1=np.copy(A)
B1=np.copy(B)
n=len(B)
print(A)
print(B)
for k in range(0,n-1):
    for i in range(k+1,n):
        mult= A[i,k]/A[k,k]
        for j in range(k,n):
            A[i,j]-=mult*A[k,j]
        B[i] -=mult*B[k]
x=np.zeros(n)
x[n-1]=B[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    suma_j=0
    for j in range(i+1,n):
        suma_j += A[i,j]*x[j]
        x[i]=(B[i]-suma_j)/A[i,i]

print("\n las soluciones del sistema de  ecuaciones  es:")
print(np.linalg.solve(A,B))

[[ 4. -1. -1.  0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]
[30. 60. 40. 70.]

 las soluciones del sistema de  ecuaciones  es:
[20.  27.5 22.5 30. ]


# Programe el método de eliminación gaussiana y halle el valor de estas temperaturas. Utilice como apoyo el ejercicio del literal anterior.

In [16]:
for k in range(n-1):
        #Elija el elemento de pivote más grande a continuación (incluido) k
        maxindex = abs(A[k:,k]).argmax()+ k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Intercambiar filas
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            B[[k,maxindex]] = B[[maxindex, k]]

# 5. Programe el pivoteo parcial en el algoritmo de eliminación gaussiana. Utilice este nuevo programa para resolver el ejercicio anterior. Compare los resultados.

In [17]:
import numpy as np
A = np.array([[0., -1., -1.,  0.],
              [-1., 4.,  0., -1.],
              [-1., 0.,  4., -1.],
              [0., -1., -1., 4.]])
B = np.array([30.,60.,40.,70.])
A1=np.copy(A)
B1=np.copy(B)
n=len(B)
print(A)
print(B)
for k in range(n-1):
        #Elija el elemento de pivote más grande a continuación (incluido) k
        maxindex = abs(A[k:,k]).argmax()+ k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Intercambiar filas
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            B[[k,maxindex]] = B[[maxindex, k]]
for k in range(0,n-1):

    for i in range(k+1,n):
        mult= A[i,k]/A[k,k]
        for j in range(k,n):
            A[i,j]-=mult*A[k,j]
        B[i] -=mult*B[k]
x=np.zeros(n)
x[n-1]=B[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    suma_j=0
    for j in range(i+1,n):
        suma_j += A[i,j]*x[j]
        x[i]=(B[i]-suma_j)/A[i,i]

print("\n las soluciones del sistema de  ecuaciones  es:")
print(np.linalg.solve(A,B))

[[ 0. -1. -1.  0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]
[30. 60. 40. 70.]

 las soluciones del sistema de  ecuaciones  es:
[-120.   -12.5  -17.5   10. ]
