# Solución al problema planteado por la compañera 

In [1]:
import numpy as np
def sor(A,b,x0,w,tol,iteMax):
    delta = 1
    xi = x0
    Q = 1/w*np.diag(np.diag(A)) + np.tril(A,-1)
    for i in range(iteMax):
        r = b - A@xi
        delta = np.linalg.solve(Q,r)
        xi = xi + delta
        if np.linalg.norm(delta) < tol:
            break
    return xi, i

In [2]:
n=1000 # número de ecuaciones
A = np.zeros([n,n])
for i in range(n):
    A[i,i] = -6 # valores de la diagonal de la matriz A
    if i < n-1:
        A[i,i+1] = 1
        A[i+1,i] = 1
A[0,0] = A[999,999] = 6
A[0,1] = A[999,998] = -1
print('\t Matriz A \n',A,'\n')
b = 60*np.ones([n]) # valores de creación del vector de términos independientes b
b[0] = b[n-1] = -30 # Valores inicial y final de b
print(b)

	 Matriz A 
 [[ 6. -1.  0. ...  0.  0.  0.]
 [ 1. -6.  1. ...  0.  0.  0.]
 [ 0.  1. -6. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -6.  1.  0.]
 [ 0.  0.  0. ...  1. -6.  1.]
 [ 0.  0.  0. ...  0. -1.  6.]] 

[-30.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.  60.
  60.  60.  

In [3]:
w = 0.5
for k in range(9):
    x0 = np.zeros_like(b) # x0 = Vector inicial
    w += 0.1
    tol = 1e-4
    iteMax = 500
    [xsor,itsor] = sor(A,b,x0,w,tol,iteMax)
    if itsor != iteMax-1:
        print('\n Con w = ','{0:.2f}'.format(w),'\t Se alcanzaron',itsor+1,'iteraciones para el método Sor','\n\n\t Las soluciones X',k+1,'\n\n',xsor.round(decimals=2))
    else:
        print('\n Con w = ','{0:.2f}'.format(w),'\t Se alcanzaron',itsor+1,' iteraciones que es el número máximo que se consideró para el método Sor','\n\n\t En la búsqueda de Las soluciones X',k+1)


 Con w =  0.60 	 Se alcanzaron 26 iteraciones para el método Sor 

	 Las soluciones X 1 

 [ -7.28 -13.68 -14.77 -14.96 -14.99 -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15


 Con w =  0.80 	 Se alcanzaron 17 iteraciones para el método Sor 

	 Las soluciones X 3 

 [ -7.28 -13.68 -14.77 -14.96 -14.99 -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15


 Con w =  1.00 	 Se alcanzaron 11 iteraciones para el método Sor 

	 Las soluciones X 5 

 [ -7.28 -13.68 -14.77 -14.96 -14.99 -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15


 Con w =  1.20 	 Se alcanzaron 11 iteraciones para el método Sor 

	 Las soluciones X 7 

 [ -7.28 -13.68 -14.77 -14.96 -14.99 -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15


 Con w =  1.40 	 Se alcanzaron 18 iteraciones para el método Sor 

	 Las soluciones X 9 

 [ -7.28 -13.68 -14.77 -14.96 -14.99 -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.   -15.
 -15.   -15

\\begin{cases}
\hphantom{-}x_1 + 1.5x{_2} \qquad\qquad\quad = 2 & \\
1.5x_i{_-{_1}} + x_i + 1.5x_i{_+{_1}} \quad= 3.5\qquad(2\leq j\leq 999) & \\
\qquad 1.5x_9{_9{_9}}+x_1{_0{_0{_0}}} \qquad= 2
\end{cases}